spring:
  profiles:
    active: local

  messages:
    basename: messages/response

  jackson:
    time-zone: Asia/Seoul

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  expiration: 3600000
